name: Pull Request Validation

on:
  pull_request:

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: "Checkout swift-sentry"
        uses: actions/checkout@v4

      - name: Install Swift
        uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.9-release
          tag: 5.9-RELEASE

      - name: Build
        run: swift build --verbose

  macOS:
    runs-on: macos-13

    steps:
      - name: "Checkout swift-sentry"
        uses: actions/checkout@v4

      - name: Select Xcode 15.0
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Build
        run: swift build --verbose
